require:
- rubocop-rails
- rubocop-performance
- rubocop-rspec
- rubocop-rake

AllCops:
  NewCops: enable
Style/Documentation:
  Enabled: false
Style/ClassVars:
  Exclude:
  - 'lib/pg_rls.rb'
Metrics/MethodLength:
  Exclude:
  - 'lib/pg_rls/schema/**/*'
  - 'lib/pg_rls/database/prepared.rb'
Metrics/BlockLength:
  Exclude:
  - 'lib/pg_rls/database/tasks/admin_database.rake'
Security/MarshalLoad:
  Exclude:
  - 'lib/pg_rls/middleware/set_reset_connection.rb'
Metrics/ModuleLength:
  Exclude:
  - 'lib/pg_rls.rb'
