---
name: thor
version: '1.2'
source:
  type: git
  name: ruby/gem_rbs_collection
  revision: 218cf130d31f63e110e350efc3fa265311b0f238
  remote: https://github.com/ruby/gem_rbs_collection.git
  repo_dir: gems
