# frozen_string_literal: true

module PgRls
  module ActiveRecord
    module ConnectionAdapters
      module PostgreSQL
        module CheckRlsUserPrivilages
          include SqlHelperMethod

          def check_rls_user_privileges!: (String, String) -> bool

          def check_table_privileges!: (String, String, String) -> bool

          def check_sequence_privileges!: (String, String, String) -> bool

          private

          def check_user_exists!: (String) -> bool

          def check_user_in_rls_group!: (String) -> bool

          def check_schema_usage_privilege!: (String, String) -> bool

          def check_default_table_privileges!: (String, String) -> bool

          def check_default_sequence_privileges!: (String, String) -> bool

          def check_user_exists_sql: (String) -> String

          def check_user_in_rls_group_sql: (String) -> String

          def check_schema_usage_privilege_sql: (String, String) -> String

          def check_default_table_privileges_sql: (String, String) -> String

          def check_table_privileges_sql: (String, String, String) -> String

          def check_default_sequence_privileges_sql: (String, String) -> String

          def check_sequence_privileges_sql: (String, String, String) -> String
        end
      end
    end
  end
end
