# frozen_string_literal: true

module PgRls
  module ActiveRecord
    module ConnectionAdapters
      module PostgreSQL
        module RlsFunctions
          include SqlHelperMethod

          def function_exists?: (String) -> bool
                                                   
          def create_rls_functions: () -> void
          
          def drop_rls_functions: () -> void
                                  
          private

          def create_function: (String, String) -> Array[PG::Result]
                             
          def drop_function: (String) -> Array[PG::Result]

          def create_tenant_id_setter_function: () -> void
                                              
          def create_tenant_id_update_blocker_function: () -> void
                                                      
          def create_rls_blocking_function: () -> void
        end
      end
    end
  end
end
