# frozen_string_literal: true

module PgRls
  module ActiveRecord
    module ConnectionAdapters
      module PostgreSQL
        module SqlHelperMethod
          private

          def execute: (String) -> Array[PG::Result]

          def transaction: (*untyped args, **untyped attr) { () ->  Array[PG::Result] } -> Array[PG::Result]

          def execute_sql!: (String) -> Array[PG::Result]

          def rescue_sql_error?: (StandardError) -> bool
        end
      end
    end
  end
end
