# frozen_string_literal: true

module PgRls
  VERSION: String

  @@schema: String | Symbol
  def self.schema: -> (String | Symbol)
  def self.schema=: (String | Symbol) -> (String | Symbol)

  @@username: String | Symbol
  def self.username: -> (String | Symbol)
  def self.username=: (String | Symbol) -> (String | Symbol)

  @@password: String | Symbol
  def self.password: -> (String | Symbol)
  def self.password=: (String | Symbol) -> (String | Symbol)
end
