# frozen_string_literal: true

module PgRls
  VERSION: String

  def self.setup: () { (untyped) -> untyped } -> untyped

  def self.main_model: () -> untyped

  @@search_methods: Array[Symbol]
  def self.search_methods: -> Array[Symbol]
  def self.search_methods=: (Array[Symbol]) -> Array[Symbol]

  @@table_name: String | Symbol
  def self.table_name: -> (String | Symbol)
  def self.table_name=: (String | Symbol) -> (String | Symbol)

  @@class_name: String | Symbol
  def self.class_name: -> (String | Symbol)
  def self.class_name=: (String | Symbol) -> (String | Symbol)

  @@username: String | Symbol
  def self.username: -> (String | Symbol)
  def self.username=: (String | Symbol) -> (String | Symbol)

  @@password: String | Symbol
  def self.password: -> (String | Symbol)
  def self.password=: (String | Symbol) -> (String | Symbol)

  @@schema: String | Symbol
  def self.schema: -> (String | Symbol)
  def self.schema=: (String | Symbol) -> (String | Symbol)
                  
  def self.mattr_accessor: (Symbol) -> untyped
end
