module PgRls
  module ActiveSupport
    module StringExt
      def sanitize_sql: -> String
                      
      def gsub!: (Regexp, String) -> String
               
      def strip!: -> String
    end
  end
end

class String
  include PgRls::ActiveSupport::StringExt
end
