---
name: activesupport
version: '7.0'
source:
  type: git
  name: ruby/gem_rbs_collection
  revision: c718a9d97695937f952c72aec0c09632e1342201
  remote: https://github.com/ruby/gem_rbs_collection.git
  repo_dir: gems
