# frozen_string_literal: true

module PgRls
  module ActiveRecord
    module ConnectionAdapters
      module RlsTenant
        UNKNOWN: Object

        attr_accessor rls_tenant_id: String | Object | nil

        private def configure_connection: () -> void

        def commit_db_transaction: () -> void

        private def exec_rollback_db_transaction: () -> void

        private def exec_restart_db_transaction: () -> void

        private def exec_rollback_to_savepoint: (?String? name) -> void

        private def aborted_transaction?: () -> bool
      end

      module ConnectionPool
        attr_reader checkout_timeout: untyped

        def checkout: (?untyped checkout_timeout) -> untyped

        def rls_connection?: () -> bool

        def pool_config: () -> untyped

        private def reset_rls_used_connections: (ActiveRecord::ConnectionAdapters::PostgreSQLAdapter conn) -> nil

      end
    end
  end

  class Tenant
    def self.reset_rls_used_connections: (ActiveRecord::ConnectionAdapters::PostgreSQLAdapter conn) -> nil

    def set_rls: (ActiveRecord::ConnectionAdapters::PostgreSQLAdapter conn) -> Tenant

  end

  module Current
    def self.tenant: () -> Tenant
  end
end

module ActiveRecord
  module ConnectionAdapters
    class ConnectionPool
      attr_reader checkout_timeout: untyped
    end
  end
end


